name: main

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"
          enable-cache: true
          ignore-nothing-to-cache: true
      - name: Run Pylint
        run: uv run pylint src --fail-under 9
      - name: Run Ruff
        run: uv run ruff check
      - name: Run Mypy
        run: uv run mypy src

  test:
    needs: [static-analysis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          ignore-nothing-to-cache: true
      - name: Run Pytest
        run: uv run pytest

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
          ignore-nothing-to-cache: true
      - name: Build package
        run: uv build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: autosar-she
          path: dist/*
          compression-level: 9
          if-no-files-found: error
