name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv python pin ${{matrix.python-version}}
          uv sync
      - name: Analysing the code with pylint
        run: |
          uv run pylint src --fail-under 8
